((magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-file-dispatch nil)
 (magit-gitignore nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-rebase nil)
 (magit-reset nil)
 (magit-revert
  ("--edit"))
 (magit-revision-history "ORIG_HEAD")
 (magit-run nil)
 (magit-show-refs nil)
 (magit-stash nil)
 (magit-tag nil))
